server:
  port: 6969
spring:
  application:
    name: provider-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:6767/eureka
logging:
  level:
    root: INFO

