security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 6767
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:password123@localhost:6767/eureka
logging:
  level:
    root: INFO
