server:
  port: 8890
spring:
  application:
    name: comsumer-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:6767/eureka
logging:
  level:
    root: INFO

