server:
  port: 8050

spring:
  application:
    name: comsumer-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:6767/eureka

logging:
  level:
    root: INFO

zuul:
  routes:
    app-a:
      path: /user/**
      serviceId: comsumer-hystrix
    app-sidecar:
      path: /sidecar/**
      serviceId: comsumer-sidecar
    app-soo:
      path: /jt/soo/**
      serviceId: Soo

